/**
 * 
 * 
 * @author ftl
 *
 */
package com.fiberhome.ms.bbs.entity;

import java.util.Date;

import com.fiberhome.smartms.model.LongIdVO;

public class Answer extends LongIdVO {
   
  /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_question_answer.QUESTION_ID
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    private long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_question_answer.USER_ID
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    private long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_question_answer.ANSWER_DATE
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    private Date answerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_question_answer.BEST_ANSWER
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    private int bestAnswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_question_answer.QUESTION_ID
     *
     * @return the value of ist..t_question_answer.QUESTION_ID
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    public long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_question_answer.QUESTION_ID
     *
     * @param questionId the value for ist..t_question_answer.QUESTION_ID
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    public void setQuestionId(long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_question_answer.USER_ID
     *
     * @return the value of ist..t_question_answer.USER_ID
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    public long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_question_answer.USER_ID
     *
     * @param userId the value for ist..t_question_answer.USER_ID
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_question_answer.ANSWER_DATE
     *
     * @return the value of ist..t_question_answer.ANSWER_DATE
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    public Date getAnswerDate() {
        return answerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_question_answer.ANSWER_DATE
     *
     * @param answerDate the value for ist..t_question_answer.ANSWER_DATE
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    public void setAnswerDate(Date answerDate) {
        this.answerDate = answerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_question_answer.BEST_ANSWER
     *
     * @return the value of ist..t_question_answer.BEST_ANSWER
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    public int getBestAnswer() {
        return bestAnswer;
    }
    private String content;
    public String getContent() {
      return content;
    }

    public void setContent(String content) {
      this.content = content;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_question_answer.BEST_ANSWER
     *
     * @param bestAnswer the value for ist..t_question_answer.BEST_ANSWER
     *
     * @generated Thu Jan 25 14:26:24 CST 2018
     */
    public void setBestAnswer(int bestAnswer) {
        this.bestAnswer = bestAnswer;
    }
}
