/**
 * 
 * 
 * @author ftl
 *
 */
package com.fiberhome.ms.bbs.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;



import com.fiberhome.smartms.annotation.Lookup;
import com.fiberhome.smartms.model.LongIdVO;

public class Article extends LongIdVO {
	/**
	 * 
	 */
	private static final long serialVersionUID = 5596664248039834482L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column ist..t_article.UER_ID
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	private long userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column ist..t_article.PLATE_ID
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	@Lookup(type = "category")
	private String plateName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column ist..t_article.ARTICLE_NAME
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */

	private String articleName;

	private String content;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column ist..t_article.POST_DATE
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	private Date postDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column ist..t_article.POST_STATE
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	private String postState;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column ist..t_article.SORT
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	private int sort;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column ist..t_article.TOP
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	private String top;

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column ist..t_article.HITS
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	private int hits;

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ist..t_article.UER_ID
	 *
	 * @return the value of ist..t_article.UER_ID
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ist..t_article.PLATE_ID
	 *
	 * @return the value of ist..t_article.PLATE_ID
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ist..t_article.PLATE_ID
	 *
	 * @param plateId
	 *            the value for ist..t_article.PLATE_ID
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ist..t_article.ARTICLE_NAME
	 *
	 * @return the value of ist..t_article.ARTICLE_NAME
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public String getArticleName() {
		return articleName;
	}

	public String getPlateName() {
		return plateName;
	}

	public void setPlateName(String plateName) {
		this.plateName = plateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ist..t_article.ARTICLE_NAME
	 *
	 * @param articleName
	 *            the value for ist..t_article.ARTICLE_NAME
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public void setArticleName(String articleName) {
		this.articleName = articleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ist..t_article.POST_DATE
	 *
	 * @return the value of ist..t_article.POST_DATE
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public Date getPostDate() {
		return postDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ist..t_article.POST_DATE
	 *
	 * @param postDate
	 *            the value for ist..t_article.POST_DATE
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ist..t_article.POST_STATE
	 *
	 * @return the value of ist..t_article.POST_STATE
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public String getPostState() {
		return postState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ist..t_article.POST_STATE
	 *
	 * @param postState
	 *            the value for ist..t_article.POST_STATE
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public void setPostState(String postState) {
		this.postState = postState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ist..t_article.SORT
	 *
	 * @return the value of ist..t_article.SORT
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public int getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ist..t_article.SORT
	 *
	 * @param sort
	 *            the value for ist..t_article.SORT
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public void setSort(int sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ist..t_article.TOP
	 *
	 * @return the value of ist..t_article.TOP
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public String getTop() {
		return top;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ist..t_article.TOP
	 *
	 * @param top
	 *            the value for ist..t_article.TOP
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public void setTop(String top) {
		this.top = top;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ist..t_article.HITS
	 *
	 * @return the value of ist..t_article.HITS
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public int getHits() {
		return hits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ist..t_article.HITS
	 *
	 * @param hits
	 *            the value for ist..t_article.HITS
	 *
	 * @generated Thu Jan 04 20:16:04 CST 2018
	 */
	public void setHits(int hits) {
		this.hits = hits;
	}
	
	
}
