package com.fiberhome.ms.bbs.entity;

import com.fiberhome.smartms.annotation.Lookup;
import com.fiberhome.smartms.model.LongIdVO;
import java.util.Date;

public class DownloadRecord extends LongIdVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_download_record.USER_ID
     *
     * @generated Fri Jan 19 15:59:21 CST 2018
     */
    private long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_download_record.RESOURCE_ID
     *
     * @generated Fri Jan 19 15:59:21 CST 2018
     */
    private long resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_download_record.DOWNLOAD_DATE
     *
     * @generated Fri Jan 19 15:59:21 CST 2018
     */
    private Date downloadDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_download_record.USER_ID
     *
     * @return the value of ist..t_download_record.USER_ID
     *
     * @generated Fri Jan 19 15:59:21 CST 2018
     */
    public long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_download_record.USER_ID
     *
     * @param userId the value for ist..t_download_record.USER_ID
     *
     * @generated Fri Jan 19 15:59:21 CST 2018
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_download_record.RESOURCE_ID
     *
     * @return the value of ist..t_download_record.RESOURCE_ID
     *
     * @generated Fri Jan 19 15:59:21 CST 2018
     */
    public long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_download_record.RESOURCE_ID
     *
     * @param resourceId the value for ist..t_download_record.RESOURCE_ID
     *
     * @generated Fri Jan 19 15:59:21 CST 2018
     */
    public void setResourceId(long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_download_record.DOWNLOAD_DATE
     *
     * @return the value of ist..t_download_record.DOWNLOAD_DATE
     *
     * @generated Fri Jan 19 15:59:21 CST 2018
     */
    public Date getDownloadDate() {
        return downloadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_download_record.DOWNLOAD_DATE
     *
     * @param downloadDate the value for ist..t_download_record.DOWNLOAD_DATE
     *
     * @generated Fri Jan 19 15:59:21 CST 2018
     */
    public void setDownloadDate(Date downloadDate) {
        this.downloadDate = downloadDate;
    }
}
