/**
 * 
 * 
 * @author ftl
 *
 */
package com.fiberhome.ms.bbs.entity;

import com.fiberhome.smartms.model.LongIdVO;

public class Person extends LongIdVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_person.USER_ID
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    private long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_person.USER_MALE
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    private String userMale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_person.USER_DESCRIPTION
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    private String userDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_person.USER_IMAGE
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    private String userImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_person.USER_ID
     *
     * @return the value of ist..t_person.USER_ID
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    public long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_person.USER_ID
     *
     * @param userId the value for ist..t_person.USER_ID
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_person.USER_MALE
     *
     * @return the value of ist..t_person.USER_MALE
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    public String getUserMale() {
        return userMale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_person.USER_MALE
     *
     * @param userMale the value for ist..t_person.USER_MALE
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    public void setUserMale(String userMale) {
        this.userMale = userMale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_person.USER_DESCRIPTION
     *
     * @return the value of ist..t_person.USER_DESCRIPTION
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    public String getUserDescription() {
        return userDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_person.USER_DESCRIPTION
     *
     * @param userDescription the value for ist..t_person.USER_DESCRIPTION
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    public void setUserDescription(String userDescription) {
        this.userDescription = userDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_person.USER_IMAGE
     *
     * @return the value of ist..t_person.USER_IMAGE
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    public String getUserImage() {
        return userImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_person.USER_IMAGE
     *
     * @param userImage the value for ist..t_person.USER_IMAGE
     *
     * @generated Wed Jan 10 09:34:32 CST 2018
     */
    public void setUserImage(String userImage) {
        this.userImage = userImage;
    }
}
