/**
 * 
 * 
 * @author ftl
 *
 */
package com.fiberhome.ms.bbs.entity;

import java.util.Date;
import java.util.List;

import com.fiberhome.smartms.model.LongIdVO;

public class Reply extends LongIdVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_reply.ARTICLE_ID
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    private long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_reply.REPLY_DATE
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    private Date replyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_reply.REPLYUER_ID
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    private long replyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_reply.TARGET_ID
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    private long targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_reply.REPLY_STATE
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    private String replyState;
    
    private String content;
    
    private String targetUserId;
    
    private String targetUserName;
    
    private String replyUserName;
    
    private String userImage;
    
	private List<Reply> replyComment;
    

    private String articleName;
    private int status;
    public String getUserImage() {
		return userImage;
	}

	public void setUserImage(String userImage) {
		this.userImage = userImage;
	}

	public String getTargetUserId() {
		return targetUserId;
	}

	public void setTargetUserId(String targetUserId) {
		this.targetUserId = targetUserId;
	}

	public String getTargetUserName() {
		return targetUserName;
	}

	public void setTargetUserName(String targetUserName) {
		this.targetUserName = targetUserName;
	}

	public String getReplyUserName() {
		return replyUserName;
	}

	public void setReplyUserName(String replyUserName) {
		this.replyUserName = replyUserName;
	}

	public List<Reply> getReplyComment() {
		return replyComment;
	}

	public void setReplyComment(List<Reply> replyComment) {
		this.replyComment = replyComment;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_reply.ARTICLE_ID
     *
     * @return the value of ist..t_reply.ARTICLE_ID
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    public long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_reply.ARTICLE_ID
     *
     * @param articleId the value for ist..t_reply.ARTICLE_ID
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    public void setArticleId(long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_reply.REPLY_DATE
     *
     * @return the value of ist..t_reply.REPLY_DATE
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    public Date getReplyDate() {
        return replyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_reply.REPLY_DATE
     *
     * @param replyDate the value for ist..t_reply.REPLY_DATE
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    public void setReplyDate(Date replyDate) {
        this.replyDate = replyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_reply.REPLYUER_ID
     *
     * @return the value of ist..t_reply.REPLYUER_ID
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    public long getReplyUserId() {
        return replyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_reply.REPLYUER_ID
     *
     * @param replyuerId the value for ist..t_reply.REPLYUER_ID
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    public void setReplyUserId(long replyUserId) {
        this.replyUserId = replyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_reply.TARGET_ID
     *
     * @return the value of ist..t_reply.TARGET_ID
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    public long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_reply.TARGET_ID
     *
     * @param targetId the value for ist..t_reply.TARGET_ID
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    public void setTargetId(long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_reply.REPLY_STATE
     *
     * @return the value of ist..t_reply.REPLY_STATE
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    public String getReplyState() {
        return replyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_reply.REPLY_STATE
     *
     * @param replyState the value for ist..t_reply.REPLY_STATE
     *
     * @generated Mon Jan 15 15:56:42 CST 2018
     */
    public void setReplyState(String replyState) {
        this.replyState = replyState;
    }

    public String getArticleName() {
      return articleName;
    }

    public void setArticleName(String articleName) {
      this.articleName = articleName;
    }

    public int getStatus() {
      return status;
    }

    public void setStatus(int status) {
      this.status = status;
    }
}
