/**
 * 
 * 
 * @author ftl
 *
 */
package com.fiberhome.ms.bbs.entity;

import java.util.List;

import com.fiberhome.smartms.model.LongIdVO;

public class Classifications extends LongIdVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ist..t_question_classfications.CLASS_NAME
     *
     * @generated Thu Jan 25 14:26:54 CST 2018
     */
  
  private List<Question> questions ;
    

    public List<Question> getQuestions() {
      return questions;
    }

    public void setQuestions(List<Question> questions) {
      this.questions = questions;
    }

    private String className;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ist..t_question_classfications.CLASS_NAME
     *
     * @return the value of ist..t_question_classfications.CLASS_NAME
     *
     * @generated Thu Jan 25 14:26:54 CST 2018
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ist..t_question_classfications.CLASS_NAME
     *
     * @param className the value for ist..t_question_classfications.CLASS_NAME
     *
     * @generated Thu Jan 25 14:26:54 CST 2018
     */
    public void setClassName(String className) {
        this.className = className;
    }
}
